[tool.black]
line-length = 80
target-version = ['py311']  # Adjust based on your Python version
skip-string-normalization = false

[tool.ruff]
line-length = 80
target-version = "py311"  # Match your project version
fix = true

# Enable all relevant rule categories
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort (import sorting)
  "B",  # bugbear (common bugs)
  "UP", # pyupgrade (upgrade syntax)
  "SIM",# simplify
  "C90",# mccabe complexity
  "N",  # pep8-naming
  "D",  # pydocstyle (docstring style)
  "PL", # pylint rules (optional but helpful)
  "RUF" # ruff-specific rules
]

# You can ignore some noise if needed
ignore = [
  "D100",  # Missing docstring in public module
  "D104",  # Missing docstring in public package
]

# Format files with these extensions
include = ["*.py"]

# Exclude typical junk
exclude = [
  ".venv",
  "__pycache__",
  ".git",
  ".mypy_cache",
  ".pytest_cache",
  "build",
  "dist"
]

[tool.docformatter]
wrap-summaries = 80
wrap-descriptions = 80
recursive = true
in-place = true

